// <auto-generated />
namespace CIS420NewWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1018172 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1018172));
        
        string IMigrationMetadata.Id
        {
            get { return "201710181653037_1018172"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
