// <auto-generated />
namespace CIS420NewWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11617 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11617));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061721039_11617"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
